### ISSUE TITLE
hi， is it possible to make a windows run-able version?

### ISSUE THREAD

**Issue by miragine** [iamyb/DAIN_ESRGAN_DeOldify#1]

**Comment by miragine** [comment]
I like your project.

**Comment by iamyb** [comment]
Hi, generally it should be OK with docker+GPU on windows even though i haven't tried it...

**Comment by miragine** [comment]
![image](https://user-images.githubusercontent.com/341854/98375745-83d97700-207d-11eb-956a-f0be9e176d8a.png)
![QQ截图20201106221528](https://user-images.githubusercontent.com/341854/98375795-9784dd80-207d-11eb-863d-82211bcea44e.png)
在window下docker初始化会报错

**Comment by miragine** [comment]
can not build success.
>docker build -t dain_esrgan_deoldify .

**Comment by miragine** [comment]
要不做一个conda的版本可行吗？

**Comment by iamyb** [comment]
> 要不做一个conda的版本可行吗？

你可以手动执行一下这条命令，然后看看什么错误。如果是linux/windows路径分隔符格式导致的，你可以改一下试试看
> /bin/bash -c "cd DAIN && git apply ../patches/dain.patch && cd .."
