### ISSUE TITLE
Step 15/26: dropbox 404 Not Found

### ISSUE THREAD

**Issue by kir3d** [iamyb/DAIN_ESRGAN_DeOldify#2]
Step 15/26 : RUN wget https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0 -O ColorizeVideo_gen.pth
 ---> Running in 2c4db3176b11
--2020-11-29 21:27:15--  https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.66.1, 2620:100:6022:1::a27d:4201
Connecting to www.dropbox.com (www.dropbox.com)|162.125.66.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/336vn9y4qwyg9yz/ColorizeVideo_gen.pth [following]
--2020-11-29 21:27:16--  https://www.dropbox.com/s/raw/336vn9y4qwyg9yz/ColorizeVideo_gen.pth
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-11-29 21:27:16 ERROR 404: Not Found.

The command '/bin/sh -c wget https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0 -O ColorizeVideo_gen.pth' returned a non-zero code: 8

**Comment by kir3d** [comment]
https://data.deepai.org/deoldify/ColorizeVideo_gen.pth

**Comment by iamyb** [comment]
> https://data.deepai.org/deoldify/ColorizeVideo_gen.pth

Updated.  Seems the official changed the URL recently. Thanks for the comment. 👍
