### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by kir3d** [iamyb/DAIN_ESRGAN_DeOldify#3]
sequence of frames 2048x1556 on DAIN part:
RuntimeError: CUDA out of memory. Tried to allocate 3.35 GiB (GPU 0; 7.93 GiB total capacity; 3.80 GiB already allocated; 3.36 GiB free; 86.36 MiB cached)

How I can split images or may be arguments for DAIN? DAIN-APP can split with padding self.

**Comment by iamyb** [comment]
something like this?  https://github.com/samdobson/image_slicer (I didn't try...) 

As I know DAIN itself can't support split, anyhow you need write some code by yourself to support such high resolution...

**Comment by kir3d** [comment]
> something like this? https://github.com/samdobson/image_slicer (I didn't try...)

something like this https://github.com/baowenbo/DAIN/issues/92#issuecomment-683567327
now I will try video crop with gap and separate both process, after will try compose
