### ISSUE TITLE
Setting additional parameters

### ISSUE THREAD

**Issue by McFalljb** [iamyb/DAIN_ESRGAN_DeOldify#4]
Is there anyway to set additional parameters such as the render factor of DeOldify?

**Comment by iamyb** [comment]
Hello, maybe you can add the _render_factor_ parameter while calling colorize_esrgan_frames which is supported by Deoldify official.

#### utils/deoldify.py
`
    video_colorizer.colorize_esrgan_frames(esrgan_image_path, deoldify_image_path)      
`

**Comment by McFalljb** [comment]
Ok awesome I was wandering if you added a way when you would just use run.py to add the argument in there but thanks for your time.
